language: node_js
node_js:
- '6'
before_install:
- chmod +x aws_credential_travis.sh
- "./aws_credential_travis.sh"
- npm install -g ask-cli
script:
- phantomjs myPhantomTest.js | ask init -p default
env:
  global:
    secure: ZA942iQugrBE37g2Fl67UXavzMMJUif1w07oKBFFlBjlgi4spXVYKjrPc3uYqHeXVW+UH1e+kxbFu4zdozdAslCiN+ag4AlCYZZK3F6wV+pmgbCblCfUyUczndq5T0rCjyTu42KEdtRZopj2cOwW99g3q6pHrsXI43oEcQNxEzCVDw8UWHF0vYPLEKk9JR3du6aTPY23nqaUEnTDAmC/R2Sp+2gySEaGmOXKDF2QQueWxiEonHpPVUsU2umn5PsGLMuAFAbuJcKR8YjEMFRTV6oFhwyBkPMjOUbK1SwkFujv+hA6xrbcz99JMxmqn/UaXDGUV/dnwEzusw7QQu4lSnb3Ti12r0W1p1hQIqDyk3zPePXInW/CpFmXLD7fjsZcw8N5arcfNmrhrs1gdR8vEWGnzouKbiAfhJCcHUijiNcjCVAHAHhcu4HRAJUn36TBlepiel8/PtVlnz+JHMnahV8KB9Duum3ExjAMC2U2SbgorYn/On1R1BrThsp+u7aisOni1s2Ki7V22ivG50H33tUAYiGAulTFUWreNPahZTFtX+bjAGFRjdTD4M8h4uOqer/G9Vp+7pYy6UhFhR+xyU3B7lg2A/ORENHT0yXhpSlTcGSekCLpYIN7dtrFvTTF2A8/czFa2sQR8EWmQKK8TEOx6W/OuM2H7cBxL6SwSSM=
